Repository ibu00024/meal-reviews-in-ranking, pull requests merged in 2025-02, with the labels that each got.

#25 Add database init script with docker-compose.yml
  .github/pull_request_template.md
  README.md
  database/init.sql
  database/initData.sql
  docker-compose.yml
Labels: Ready To Review

#27 Development show restaurant
  client/package-lock.json
  client/package.json
  client/src/App.css
  client/src/App.tsx
  client/src/__tests__/HomePage.test.tsx
  client/src/__tests__/StarRating.test.tsx
  client/src/__tests__/setupTests.ts
  client/src/components/RestaurantCard.tsx
  client/src/components/StarRating.tsx
  client/src/index.css
  client/src/pages/HomePage.tsx
  client/vitest.config.ts
Labels: Ready To Review

#29 Get review by ranking
  docker-compose.yml
  server/.env.example
  server/config/server_config.ts
  server/controllers/restaurantController.ts
  server/migrations/1738913552906-InitializeData.ts
  server/models/category.ts
  server/models/homePageRestaurantData.ts
  server/models/restaurant.ts
  server/models/review.ts
  server/repositories/restaurantRepository.ts
  server/repositories/reviewRepository.ts
  server/services/restaurantService.ts
  server/utils/mySQLConnection.ts
Labels: Ready To Review

#31 Image uploader
  docker-compose.yml
  server/.env.example
  server/app.ts
  server/bucket-policy.json
  server/config/config.ts
  server/config/databaseConfig.ts
  server/config/ioc_config.ts
  server/config/minioConfig.ts
  server/config/serverConfig.ts
  server/constants/identifiers.ts
  server/controllers/imageController.ts
  server/package-lock.json
  server/package.json
  server/repositories/imageRepository.ts
  server/routes/imageRoutes.ts
  server/services/imageService.ts
  server/utils/minioConnection.ts
Labels: Ready To Review

#35 Search bar
  client/src/__tests__/SearchBar.test.tsx
  client/src/components/SearchBar.tsx
  client/src/index.css
  client/src/pages/HomePage.tsx
Labels: Ready To Review

#48 Add restaurant
  server/config/ioc_config.ts
  server/constants/identifiers.ts
  server/controllers/restaurantController.ts
  server/package-lock.json
  server/package.json
  server/repositories/restaurantRepository.ts
  server/routes/restaurantRoutes.ts
  server/services/mapService.ts
  server/services/restaurantService.ts
Labels: Backend

#49 Submit review
  server/app.ts
  server/config/ioc_config.ts
  server/constants/identifiers.ts
  server/controllers/categoryController.ts
  server/controllers/restaurantController.ts
  server/controllers/reviewController.ts
  server/models/DTO/categoryDTO.ts
  server/models/DTO/reviewSubmitDTO.ts
  server/models/category.ts
  server/models/restaurant.ts
  server/models/review.ts
  server/repositories/categoryRepository.ts
  server/repositories/imageRepository.ts
  server/repositories/restaurantRepository.ts
  server/repositories/reviewRepository.ts
  server/routes/reviewRoutes.ts
  server/services/imageService.ts
  server/services/mapService.ts
  server/services/restaurantService.ts
  server/services/reviewService.ts
Labels: Backend, Ready To Review
